version: '3'

services:
  xds-server:
    build:
      context: .
      dockerfile: Dockerfile-xds-server
    # command: "sh -c 'while true; do sleep 1000; done'"
    # command: "sh -c 'dlv debug Envoy-Pilot/cmd/server/ -l 0.0.0.0:2345 --headless=true --log=true -- server'"
    # command: "sh -c 'go run /go/src/Envoy-Pilot/cmd/server/main.go'"
    security_opt:
      - seccomp:unconfined
    volumes:
      - $PWD/env_values.txt:/.env
    expose:
      - 7777
      - 2345
    ports: 
      - "2345:2345"
      - "9090:9090"
      - "7777:7777"
      - "8081:8081"
    networks:
      - envoy-pilot_xds-demo

networks:
  envoy-pilot_xds-demo:
    external: true